services:
  kafka:
    #image: confluentinc/cp-kafka:7.5.0
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      # Konfiguracja trybu KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'

      # KLUCZOWE DLA KOMUNIKACJI MIĘDZY MASZYNAMI:
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://192.168.x.x:9092'

      # Wymagane dla KRaft
      KAFKA_CLUSTER_ID: 'MkU3OEVBNTcwNTJDRDk1Qg'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_HEAP_OPTS: "-Xms512M -Xmx512M"
      
